version: '3'
services:
  web:
   build: nginx/
   ports:
   - 8080:80
   volumes:
   - ./nginx/:/usr/share/nginx/html/
  nodeapp:
   build: nodeapp/
   volumes:
   - ./nodeapp/:/usr/src/app

  db:
   image: postgres:9.4
   restart: always
   tty: true
   volumes:
   - .pgdata:/var/lib/postgresql/data
   environment:
   - POSTGRES_PASSWORD=root
   - POSTGRES_DB=codebanck
   ports:
   - "5432:5432"